/**
 * TDV BTL MAFIA - 72 Official Achievements Registry
 * Mechanically concrete, measurable in-game objectives organized across 5 calibrated tiers:
 * BRONZE (8), SILVER (22), GOLD (24), PLATINUM (11), LEGENDARY (7).
 */

import { Achievement } from '../types/achievements';

export const ACHIEVEMENTS_REGISTRY: readonly Achievement[] = [
  // ─────────────────────────────────────────────────────────────────────────────
  // 1. ŞƏHƏR İTTİFAQI (TOWN - 15)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'town_sheriff_first_bust',
    title: "Al-Qırmızı Tədqiqat (A Study in Scarlet)",
    description: "Şərif olaraq 1-ci raundun gecəsində yoxladığın ilk oyunçunun kimliyinin 'Mafioz' çıxması.",
    category: 'TOWN',
    tier: 'BRONZE',
    icon: 'fa-magnifying-glass',
    xp: 150,
    coinReward: 50,
  },
  {
    id: 'town_doctor_miracle_save',
    title: "Hipokrat Andı (The Hippocratic Oath)",
    description: 'Həkim olaraq gecə Mafiyanın hücum etdiyi oyunçunu qoruyub onun sağ qalmasını təmin et.',
    category: 'TOWN',
    tier: 'SILVER',
    icon: 'fa-user-doctor',
    xp: 300,
    coinReward: 100,
  },
  {
    id: 'town_mayor_triple_hammer',
    title: "Leviathan (Mütləq Hakimiyyət)",
    description: 'Bələdiyyə Sədri kimi səlahiyyətini elan edərək 3-qat səs (x3) hüququ ilə Mafiya üzvünü məhkəmədə edam et.',
    category: 'TOWN',
    tier: 'GOLD',
    icon: 'fa-landmark',
    xp: 500,
    coinReward: 200,
  },
  {
    id: 'town_bodyguard_noble_sacrifice',
    title: "Üç Müşketyor (Biri Hamı Üçün)",
    description: 'Cangüdən olaraq qoruduğun şəhərliyə hücum edən qatili öldürüb onun yerinə şəhid ol.',
    category: 'TOWN',
    tier: 'SILVER',
    icon: 'fa-user-shield',
    xp: 350,
    coinReward: 120,
  },
  {
    id: 'town_veteran_double_kill',
    title: "Termopil (300 Spartalı)",
    description: "Qazi olaraq gecə 'Döyüş Həyəcanı' aktiv edib evinə daxil olan ən azı 2 cinayətkarı eyni gecədə məhv et.",
    category: 'TOWN',
    tier: 'PLATINUM',
    icon: 'fa-medal',
    xp: 850,
    coinReward: 400,
  },
  {
    id: 'town_detective_track_killer',
    title: "Baskervillərin İti (The Hound of the Baskervilles)",
    description: 'Xəfiyyə olaraq gecə qətlə yetirilən vətəndaşın evinə daxil olmuş qatilin izini aşkar et.',
    category: 'TOWN',
    tier: 'SILVER',
    icon: 'fa-binoculars',
    xp: 300,
    coinReward: 100,
  },
  {
    id: 'town_coroner_weapon_analysis',
    title: "Sümük Kolleksiyaçısı (The Bone Collector)",
    description: 'Məhkəmə eksperti olaraq qətl qurbanının cəsədini araşdırıb ölüm səbəbini və cinayət alətini təsdiqlə.',
    category: 'TOWN',
    tier: 'BRONZE',
    icon: 'fa-microscope',
    xp: 200,
    coinReward: 60,
  },
  {
    id: 'town_citizen_decisive_vote',
    title: "12 Qəzəbli Kişi (12 Angry Men)",
    description: 'Sıravi Vətəndaş kimi məhkəmədə bərabərlik olan anda sonuncu səsi verərək Mafiya üzvünün edamını təmin et.',
    category: 'TOWN',
    tier: 'BRONZE',
    icon: 'fa-users',
    xp: 250,
    coinReward: 80,
  },
  {
    id: 'town_martyr_take_the_bullet',
    title: "Müqəddəs İohan (Janna d'Ark)",
    description: 'Fədai olaraq Şərif və ya Həkimə yönəlmiş ölümcül gecə zərbəsini öz üzərinə götürərək onları qurtar.',
    category: 'TOWN',
    tier: 'SILVER',
    icon: 'fa-shield-heart',
    xp: 350,
    coinReward: 120,
  },
  {
    id: 'town_investigator_cross_faction',
    title: "Da Vinçi Şifrəsi (The Da Vinci Code)",
    description: 'Şəhər Müstəntiqi olaraq iki şübhəlinin eyni cinayətkar fraksiyaya aid olduğunu təsdiqlə.',
    category: 'TOWN',
    tier: 'GOLD',
    icon: 'fa-fingerprint',
    xp: 550,
    coinReward: 220,
  },
  {
    id: 'town_flawless_victory',
    title: 'Utopiya (Utopia)',
    description: 'Şəhər İttifaqı olaraq heç bir vətəndaş itirmədən (0 məsum ölüm) bütün düşmənləri məhv edərək qalib gəl.',
    category: 'TOWN',
    tier: 'LEGENDARY',
    icon: 'fa-crown',
    xp: 2000,
    coinReward: 1200,
  },
  {
    id: 'town_sheriff_hat_trick',
    title: 'Üçqat İfşa',
    description: 'Şərif olaraq tək oyunda 3 fərqli cinayətkarı (Mafiya və ya Neytral Qatil) gecə araşdırması ilə ifşa et.',
    category: 'TOWN',
    tier: 'PLATINUM',
    icon: 'fa-scale-balanced',
    xp: 900,
    coinReward: 450,
  },
  {
    id: 'town_doctor_double_save',
    title: "Həyat Ağacı (The Tree of Life)",
    description: 'Həkim olaraq eyni oyunda 2 fərqli raundda qətl hədəflərini uğurla qoru və ölümdən xilas et.',
    category: 'TOWN',
    tier: 'GOLD',
    icon: 'fa-heart-pulse',
    xp: 600,
    coinReward: 250,
  },
  {
    id: 'town_acquit_the_innocent',
    title: 'Bülbülü Öldürmək (To Kill a Mockingbird)',
    description: "Məhkəmə kürsüsündə günahsız vətəndaşa qarşı keçirilən səsvermədə 'Bəraət' səs verərək onun asılmasının qarşısını al.",
    category: 'TOWN',
    tier: 'BRONZE',
    icon: 'fa-handshake-angle',
    xp: 200,
    coinReward: 60,
  },
  {
    id: 'town_unanimous_conviction',
    title: "Kütlələrin Üsyanı (The Revolt of the Masses)",
    description: 'Məhkəmə mərhələsində masadakı bütün canlı şəhərlilərin eyni Mafiya namizədinə 100% səs verməsi.',
    category: 'TOWN',
    tier: 'SILVER',
    icon: 'fa-gavel',
    xp: 350,
    coinReward: 130,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 2. MAFİYA AİLƏSİ (MAFIA - 15)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'mafia_godfather_pass_sheriff',
    title: "Şeytanın Vəkili (The Devil's Advocate)",
    description: "Don olaraq Şərif tərəfindən araşdırıldıqda sistemdə 'Məsum Vətəndaş' olaraq qeydə alın.",
    category: 'MAFIA',
    tier: 'GOLD',
    icon: 'fa-masks-theater',
    xp: 500,
    coinReward: 200,
  },
  {
    id: 'mafia_first_blood',
    title: 'Karamazov Qardaşları (Brothers Karamazov)',
    description: 'Mafiya ailəsi olaraq 1-ci raundun gecəsində qətl əmrini uğurla icra et.',
    category: 'MAFIA',
    tier: 'BRONZE',
    icon: 'fa-skull-crossbones',
    xp: 150,
    coinReward: 50,
  },
  {
    id: 'mafia_consort_block_doctor',
    title: "Ölümcül Cazibə (Fatal Attraction)",
    description: 'İllüziyaçı olaraq Həkimi gecə blokla və Mafiyanın seçdiyi hədəfin müdafiəsiz qalmasını təmin et.',
    category: 'MAFIA',
    tier: 'SILVER',
    icon: 'fa-wand-magic-sparkles',
    xp: 300,
    coinReward: 120,
  },
  {
    id: 'mafia_blackmail_the_sheriff',
    title: 'Sükutun Səsi (The Sound of Silence)',
    description: 'Şantajçı olaraq Şərifi şantaj et və onun növbəti gündüz məclisində danışmasına mane ol.',
    category: 'MAFIA',
    tier: 'SILVER',
    icon: 'fa-envelope-open-text',
    xp: 350,
    coinReward: 130,
  },
  {
    id: 'mafia_puppeteer_deflection',
    title: 'Şahzadə (The Prince)',
    description: 'Kuklaçı olaraq şəhər müdafiəçisinin və ya qatilinin gecə hərəkətini başqa hədəfə yönləndir.',
    category: 'MAFIA',
    tier: 'GOLD',
    icon: 'fa-mask',
    xp: 550,
    coinReward: 220,
  },
  {
    id: 'mafia_forger_alter_evidence',
    title: '1984',
    description: 'Saxtakar Katib kimi ölmüş oyunçunun vəsiyyətnaməsini səhər qəzetində uğurla saxtalaşdır.',
    category: 'MAFIA',
    tier: 'GOLD',
    icon: 'fa-pen-nib',
    xp: 600,
    coinReward: 250,
  },
  {
    id: 'mafia_framer_deception',
    title: "Dreyfus İşi (The Dreyfus Affair)",
    description: "Şər Atan kimi günahsız vətəndaşı çərçivəyə salaraq Şərifin onu 'Mafioz' görməsinə nail ol.",
    category: 'MAFIA',
    tier: 'SILVER',
    icon: 'fa-file-signature',
    xp: 400,
    coinReward: 150,
  },
  {
    id: 'mafia_don_last_man_standing',
    title: 'Xaçatası (The Godfather)',
    description: 'Bütün mafiya yoldaşların edam edildikdən sonra Don olaraq təkbaşına sağ qalıb qələbə qazan.',
    category: 'MAFIA',
    tier: 'PLATINUM',
    icon: 'fa-crown',
    xp: 900,
    coinReward: 450,
  },
  {
    id: 'mafia_bypass_protective_shield',
    title: "Axillesin Dabanı (Achilles' Heel)",
    description: 'Masada Həkim və Cangüdən olduğu halda onların qorumadığı vətəndaşı seçərək qətl törət.',
    category: 'MAFIA',
    tier: 'SILVER',
    icon: 'fa-crosshairs',
    xp: 350,
    coinReward: 130,
  },
  {
    id: 'mafia_clean_sweep',
    title: "Kosa Nostra (Cosa Nostra)",
    description: 'Mafiya ailəsinin heç bir üzvü öldürülmədən və edam edilmədən oyunu tam qələbə ilə bitir.',
    category: 'MAFIA',
    tier: 'LEGENDARY',
    icon: 'fa-trophy',
    xp: 1800,
    coinReward: 1000,
  },
  {
    id: 'mafia_tactical_sacrifice',
    title: "Brutun Xəncəri (The Dagger of Brutus)",
    description: 'Özünü gizlətmək üçün məhkəmədə şübhə altına düşmüş digər mafiozun edamına səs verərək etimad qazan.',
    category: 'MAFIA',
    tier: 'GOLD',
    icon: 'fa-chess-pawn',
    xp: 500,
    coinReward: 200,
  },
  {
    id: 'mafia_triple_night_kills',
    title: "Varfolomey Gecəsi (St. Bartholomew's Day Massacre)",
    description: 'All-In və ya böyük rejimdə tək gecədə təyin olunmuş 3 qətl limitinin hamısını uğurla tamamla.',
    category: 'MAFIA',
    tier: 'PLATINUM',
    icon: 'fa-bolt',
    xp: 900,
    coinReward: 400,
  },
  {
    id: 'mafia_parity_domination',
    title: "Şah Mat (Checkmate)",
    description: 'Masadakı canlı Mafiya sayını vətəndaş sayına çatdıraraq (50%-ə qarşı 50%) oyunu dərhal bitir.',
    category: 'MAFIA',
    tier: 'GOLD',
    icon: 'fa-city',
    xp: 600,
    coinReward: 250,
  },
  {
    id: 'mafia_enforcer_ascend',
    title: "Kral Öldü, Yaşasın Kral!",
    description: 'Sıravi Mafioz kimi Don öldükdən sonra ailənin yeni rəhbəri olaraq oyunu qələbəyə daşı.',
    category: 'MAFIA',
    tier: 'SILVER',
    icon: 'fa-gun',
    xp: 400,
    coinReward: 150,
  },
  {
    id: 'mafia_secret_night_orders',
    title: "Gecəyarısı Şurası (The Midnight Council)",
    description: 'Mafiya komandası ilə gecə bufferi bitməmiş bütün qətl əmrlərini yekdilliklə təsdiqlə.',
    category: 'MAFIA',
    tier: 'BRONZE',
    icon: 'fa-user-secret',
    xp: 200,
    coinReward: 70,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 3. NEYTRAL VƏ XAOS (NEUTRAL - 12)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'neutral_jester_early_execution',
    title: "Axmaqların Gəmisi (Ship of Fools)",
    description: 'Dəli (Jester) olaraq ilk 2 raund ərzində şəhər məhkəməsi tərəfindən asılaraq təkbaşına qalib gəl.',
    category: 'NEUTRAL',
    tier: 'PLATINUM',
    icon: 'fa-face-laugh-squint',
    xp: 1000,
    coinReward: 500,
  },
  {
    id: 'neutral_jester_curse_delivered',
    title: "Hamletin Kabusu (Hamlet's Ghost)",
    description: "Dəli kimi edam edildikdən sonra sənə 'Edam' səs vermiş oyunçulardan birini gecə məzara apar.",
    category: 'NEUTRAL',
    tier: 'GOLD',
    icon: 'fa-skull',
    xp: 550,
    coinReward: 220,
  },
  {
    id: 'neutral_sk_deflect_mafia',
    title: "Ölümsüz (The Immortal)",
    description: 'Seriyalı Qatil olaraq gecə Mafiyanın hücumuna tuş gəl və daxili zireh sayəsində sağ qal.',
    category: 'NEUTRAL',
    tier: 'SILVER',
    icon: 'fa-shield',
    xp: 350,
    coinReward: 140,
  },
  {
    id: 'neutral_sk_triple_kill_streak',
    title: "Dorian Qreyin Portreti (The Picture of Dorian Gray)",
    description: 'Seriyalı Qatil kimi ardıcıl 3 gecə fasiləsiz olaraq hədəflərini məhv et.',
    category: 'NEUTRAL',
    tier: 'PLATINUM',
    icon: 'fa-knife',
    xp: 950,
    coinReward: 480,
  },
  {
    id: 'neutral_sk_sole_survivor',
    title: 'Yad (The Stranger)',
    description: 'Masadakı bütün Mafiya və Şəhər sakinlərini məhv edərək sağ qalan tək canlı oyunçu ol.',
    category: 'NEUTRAL',
    tier: 'LEGENDARY',
    icon: 'fa-fire',
    xp: 2200,
    coinReward: 1400,
  },
  {
    id: 'neutral_arsonist_triple_blaze',
    title: 'Cəhənnəm Alovu',
    description: 'Yandırıcı (Arsonist) olaraq eyni gecədə ən azı 3 benzinlənmiş evi alova bürüyərək məhv et.',
    category: 'NEUTRAL',
    tier: 'LEGENDARY',
    icon: 'fa-fire-flame-curved',
    xp: 2000,
    coinReward: 1200,
  },
  {
    id: 'neutral_amnesiac_become_town',
    title: "İtirilmiş Zamanın Axtarışında (In Search of Lost Time)",
    description: 'Kimlik Axtaran kimi ölmüş Şəhər İttifaqı rolunu (Şərif, Həkim və s.) mənimsəyərək Şəhərlə qalib gəl.',
    category: 'NEUTRAL',
    tier: 'SILVER',
    icon: 'fa-shield-halved',
    xp: 400,
    coinReward: 160,
  },
  {
    id: 'neutral_amnesiac_become_mafia',
    title: "Doktor Cekil və Mister Hayd",
    description: 'Kimlik Axtaran kimi ölmüş Mafiozun rolunu mənimsəyərək Mafiya Ailəsi ilə qalib gəl.',
    category: 'NEUTRAL',
    tier: 'GOLD',
    icon: 'fa-brain',
    xp: 600,
    coinReward: 250,
  },
  {
    id: 'neutral_witch_redirect_killer',
    title: "Makbetin Cadugərləri (The Witches of Macbeth)",
    description: 'Cadugər kimi Seriyalı Qatilin hücumunu Mafiya üzvünə yönləndirərək cinayətkarı məhv et.',
    category: 'NEUTRAL',
    tier: 'PLATINUM',
    icon: 'fa-wand-sparkles',
    xp: 850,
    coinReward: 400,
  },
  {
    id: 'neutral_yakuza_clan_victory',
    title: 'Müharibə Sənəti (The Art of War)',
    description: 'Yakuza Klanı olaraq həm İtalyan Mafiyasını, həm də Şəhəri qabaqlayıb qələbə qazan.',
    category: 'NEUTRAL',
    tier: 'GOLD',
    icon: 'fa-dragon',
    xp: 650,
    coinReward: 280,
  },
  {
    id: 'neutral_void_cult_ritual',
    title: 'Ktulhu Çağırışı (Call of Cthulhu)',
    description: 'Boşluq Təriqətçisi olaraq 3 fərqli oyunçunu qaranlıq ayinlə işarələyib portalı aç.',
    category: 'NEUTRAL',
    tier: 'PLATINUM',
    icon: 'fa-eye',
    xp: 900,
    coinReward: 450,
  },
  {
    id: 'neutral_survivor_five_rounds',
    title: "Robinzon Kruzo (Robinson Crusoe)",
    description: 'Heç bir qətl və ya edam hücumuna tuş gəlmədən ən azı 5 raund həyatda qal.',
    category: 'NEUTRAL',
    tier: 'SILVER',
    icon: 'fa-scale-unbalanced',
    xp: 400,
    coinReward: 160,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 4. XÜSUSİ REJİMLƏR VƏ MİNİ-OYUNLAR (MODES - 16)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'mode_inferno_cocytus_conquest',
    title: '9 Dairə Zəfəri',
    description: "Dante's Inferno rejimində bütün 9 cəhənnəm dairəsini (Limbo-dan Cocytus-a qədər) canlı başa vur.",
    category: 'MODES',
    tier: 'LEGENDARY',
    icon: 'fa-snowflake',
    xp: 2200,
    coinReward: 1500,
  },
  {
    id: 'mode_inferno_heresy_solve',
    title: 'Heresy İpucu',
    description: 'Dante rejiminin Heresy dairəsində sızan xüsusi ipucu ilə cinayətkarın kimliyini ifşa et.',
    category: 'MODES',
    tier: 'SILVER',
    icon: 'fa-key',
    xp: 350,
    coinReward: 140,
  },
  {
    id: 'mode_inferno_greed_gold_vote',
    title: 'Tamahkarın Qızılı',
    description: 'Greed dairəsində səs borcunu qızıl sikkələrlə bağlayaraq məhkəmə edamından qurtul.',
    category: 'MODES',
    tier: 'GOLD',
    icon: 'fa-coins',
    xp: 550,
    coinReward: 230,
  },
  {
    id: 'mode_earth_klaatu_activation',
    title: 'Klaatu Dondurması',
    description: "The Day The Earth Stood Still rejimində 'World Freeze' qabiliyyətini aktivləşdirərək qətli blokla.",
    category: 'MODES',
    tier: 'GOLD',
    icon: 'fa-icicles',
    xp: 600,
    coinReward: 250,
  },
  {
    id: 'mode_earth_doomsday_hour_eleven',
    title: 'Qiyamət Ərəfəsi',
    description: 'Doomsday Saatı 11-ci saata çatdığı kritik vəziyyətdə son mafiozu edam edərək dünyanı xilas et.',
    category: 'MODES',
    tier: 'PLATINUM',
    icon: 'fa-clock-rotate-left',
    xp: 900,
    coinReward: 450,
  },
  {
    id: 'mode_valkyrie_defuse_the_briefcase',
    title: 'Valkyrie Çamadanı',
    description: 'Operation Valkyrie rejimində partlayıcı çamadanın olduğu oyunçunu aşkar edib fitili zərərsizləşdir.',
    category: 'MODES',
    tier: 'GOLD',
    icon: 'fa-briefcase',
    xp: 650,
    coinReward: 280,
  },
  {
    id: 'mode_valkyrie_overthrow_dictator',
    title: 'Diktatorun Sonu',
    description: 'Valkyrie rejimində Diktator rolunu oynayan şəxsi məhkəmə səsverməsi ilə vəzifəsindən kənarlaşdır.',
    category: 'MODES',
    tier: 'SILVER',
    icon: 'fa-person-falling-burst',
    xp: 400,
    coinReward: 150,
  },
  {
    id: 'mode_stanford_revolt_maximum',
    title: 'Stanford Qiyamı',
    description: 'Stanford Prison rejimində Qiyam Sayğacını 100%-ə çatdıraraq Məhbus fraksiyası ilə zəfər qazan.',
    category: 'MODES',
    tier: 'GOLD',
    icon: 'fa-link-slash',
    xp: 700,
    coinReward: 300,
  },
  {
    id: 'mode_catenaccio_defense_barrier',
    title: 'Catenaccio Səddi',
    description: 'Catenaccio rejimində 4 nəfərlik Müdafiə Divarını keçməyə çalışan Snayperi vaxtında aşkar et.',
    category: 'MODES',
    tier: 'SILVER',
    icon: 'fa-shield-halved',
    xp: 400,
    coinReward: 160,
  },
  {
    id: 'mode_chernobyl_decontamination',
    title: 'Dozimetr Nəzarəti',
    description: 'Çernobıl rejimində Dozimetrist olaraq radiasiya mutantlarının kimliyini ifşa et.',
    category: 'MODES',
    tier: 'GOLD',
    icon: 'fa-biohazard',
    xp: 600,
    coinReward: 250,
  },
  {
    id: 'mode_cyberpunk_hack_the_net',
    title: 'Kiber-Təqib',
    description: 'Cyberpunk 2077: Neo-Bakı rejimində qara şəbəkə qatilinin neyro-izini taparaq zərərsizləşdir.',
    category: 'MODES',
    tier: 'GOLD',
    icon: 'fa-network-wired',
    xp: 650,
    coinReward: 280,
  },
  {
    id: 'mode_bermuda_triangle_solve',
    title: 'Bermud Kompası',
    description: 'Bermud Üçbucağı rejimində Şturman Naviqator olaraq ruh quldurlarının yerləşdiyi gəmini tap.',
    category: 'MODES',
    tier: 'SILVER',
    icon: 'fa-anchor',
    xp: 350,
    coinReward: 140,
  },
  {
    id: 'mode_baker_street_takedown',
    title: 'Holmsun Qələbəsi',
    description: 'Baker Street rejimində Moriarti Şəbəkəsini 3 raund tamamlanmamış tam məhv et.',
    category: 'MODES',
    tier: 'PLATINUM',
    icon: 'fa-magnifying-glass-chart',
    xp: 950,
    coinReward: 480,
  },
  {
    id: 'mode_all_in_dual_lock_unlock',
    title: 'İkiqat İnzibati Kilid',
    description: 'All-In 40–50 nəfərlik rejimdə Arxitektor və ya Məhkəmə İcraçısı açarını rəsmən təsdiqlə.',
    category: 'MODES',
    tier: 'GOLD',
    icon: 'fa-compass-drafting',
    xp: 750,
    coinReward: 320,
  },
  {
    id: 'mode_all_in_regional_champion',
    title: 'Kvartal Nümayəndəsi',
    description: 'All-In rejimində Regional Caucus mərhələsində kvartalından mərkəzi palataya nümayəndə seçil.',
    category: 'MODES',
    tier: 'SILVER',
    icon: 'fa-landmark-flag',
    xp: 450,
    coinReward: 180,
  },
  {
    id: 'mode_all_in_grand_finish',
    title: 'Böyük All-In Zəfəri',
    description: '40+ nəfərlik Meqapolis All-In oyununda öz fraksiyanla yekun qələbə qazan.',
    category: 'MODES',
    tier: 'LEGENDARY',
    icon: 'fa-gem',
    xp: 2500,
    coinReward: 1600,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 5. USTALIQ VƏ TƏCRÜBƏ (MASTERY - 14)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'mastery_flawless_defense_speech',
    title: 'Qızıl Müdafiə',
    description: 'Məhkəmə kürsüsündə ittiham olunarkən 30 saniyəlik müdafiə çıxışından sonra bəraət qazan.',
    category: 'MASTERY',
    tier: 'GOLD',
    icon: 'fa-bullhorn',
    xp: 600,
    coinReward: 250,
  },
  {
    id: 'mastery_first_time_host',
    title: 'Masa Rəhbəri',
    description: 'Host olaraq ilk oyun masasını yarat və ən azı 4 oyunçu ilə oyunu uğurla başlat.',
    category: 'MASTERY',
    tier: 'BRONZE',
    icon: 'fa-crown',
    xp: 200,
    coinReward: 70,
  },
  {
    id: 'mastery_five_room_host',
    title: 'Təcrübəli Təşkilatçı',
    description: "Masa Rəhbəri kimi 5 fərqli oyunu 'ENDED' (Tamamlandı) fazasına qədər idarə et.",
    category: 'MASTERY',
    tier: 'SILVER',
    icon: 'fa-list-check',
    xp: 400,
    coinReward: 160,
  },
  {
    id: 'mastery_voice_chat_orator',
    title: 'Canlı Səs Natiqi',
    description: 'WebRTC canlı səsli rabitə aktiv olan oyunda məhkəmə müzakirəsində iştirak edərək qalib gəl.',
    category: 'MASTERY',
    tier: 'SILVER',
    icon: 'fa-microphone',
    xp: 350,
    coinReward: 140,
  },
  {
    id: 'mastery_three_win_streak',
    title: 'Bürünc Qələbə Seriyası',
    description: 'Ard-arda 3 oyunda fasiləsiz qələbə qazan.',
    category: 'MASTERY',
    tier: 'SILVER',
    icon: 'fa-forward-step',
    xp: 450,
    coinReward: 180,
  },
  {
    id: 'mastery_five_win_streak',
    title: 'Gümüş Qələbə Seriyası',
    description: 'Ard-arda 5 oyunda fasiləsiz qələbə qazan.',
    category: 'MASTERY',
    tier: 'GOLD',
    icon: 'fa-fire',
    xp: 800,
    coinReward: 350,
  },
  {
    id: 'mastery_ten_win_streak',
    title: 'Qızıl Rekord Seriyası',
    description: 'Ard-arda 10 oyunda məğlub olmadan qalib gələrək lisey rekordunu vur.',
    category: 'MASTERY',
    tier: 'LEGENDARY',
    icon: 'fa-trophy',
    xp: 3000,
    coinReward: 2000,
  },
  {
    id: 'mastery_ten_games_played',
    title: 'Aktiv Şəhərli',
    description: 'Ümumilikdə 10 tam mafiya oyununda iştirak et.',
    category: 'MASTERY',
    tier: 'BRONZE',
    icon: 'fa-id-card',
    xp: 250,
    coinReward: 90,
  },
  {
    id: 'mastery_fifty_games_played',
    title: 'Lisey Veteranı',
    description: 'Ümumilikdə 50 tam mafiya oyunu tamamla.',
    category: 'MASTERY',
    tier: 'GOLD',
    icon: 'fa-shield-halved',
    xp: 900,
    coinReward: 400,
  },
  {
    id: 'mastery_hundred_games_played',
    title: 'Mafiya Əfsanəsi',
    description: 'Ümumilikdə 100 tam mafiya oyunu başa vur.',
    category: 'MASTERY',
    tier: 'LEGENDARY',
    icon: 'fa-medal',
    xp: 3500,
    coinReward: 2500,
  },
  {
    id: 'mastery_anti_afk_sentinel',
    title: 'Dəmir İntizam',
    description: '20 oyun boyunca bir dəfə də olsun AFK qalmadan bütün gecə və gündüz fazalarında iştirak et.',
    category: 'MASTERY',
    tier: 'SILVER',
    icon: 'fa-user-check',
    xp: 450,
    coinReward: 200,
  },
  {
    id: 'mastery_five_thousand_coins',
    title: 'Böyük Qetsbi (The Great Gatsby)',
    description: 'Qələbələrdən və tamamlanan nailiyyətlərdən ümumilikdə 5,000 🪙 qızıl topla.',
    category: 'MASTERY',
    tier: 'PLATINUM',
    icon: 'fa-coins',
    xp: 1200,
    coinReward: 600,
  },
  {
    id: 'mastery_ten_thousand_coins',
    title: 'Uoll Strit Canavarı',
    description: 'Oyun daxilində ümumilikdə 10,000 🪙 qızıl balansına sahib ol.',
    category: 'MASTERY',
    tier: 'LEGENDARY',
    icon: 'fa-sack-dollar',
    xp: 2500,
    coinReward: 1500,
  },
  {
    id: 'mastery_all_modes_played',
    title: 'Formatlar Ustası',
    description: 'Mövcud olan bütün 15 oyun formatında ən azı 1 tam oyun oyna.',
    category: 'MASTERY',
    tier: 'PLATINUM',
    icon: 'fa-compass',
    xp: 1500,
    coinReward: 800,
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 6. LEGENDARY / LOR (Cinematic Achievements)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'legacy_seven_deadly_sins',
    title: 'Blitz',
    description: "Oyunu düz 7 nəfər sağ qalaraq başa vur və 7 ölümcül günahkarın sonuncusu kimi xilas ol.",
    category: 'MODES',
    tier: 'LEGENDARY',
    icon: 'fa-skull',
    xp: 2000,
    coinReward: 500,
  },
  {
    id: 'legacy_and_then_there_were_none',
    title: 'Standart (8-11)',
    description: "Aqata Kristi stili: Masadakı hər kəs edam edildikdən və ya öldürüldükdən sonra təkbaşına sağ qalan yeganə oyunçu ol.",
    category: 'MASTERY',
    tier: 'LEGENDARY',
    icon: 'fa-chess-king',
    xp: 2500,
    coinReward: 750,
  },
  {
    id: 'legacy_crime_and_punishment',
    title: 'Crime and Punishment',
    description: "Bir oyunda ən azı 15 nəfər edam edildikdə və ya cəzalandırıldıqda qalib tərəfdə ol.",
    category: 'TOWN',
    tier: 'PLATINUM',
    icon: 'fa-scale-balanced',
    xp: 1000,
    coinReward: 300,
  },
  {
    id: 'legacy_steins_gate',
    title: 'Steins;Gate',
    description: "Məhkəmədə tam asılarkən son saniyədə (Time Leap) səsvermə trayektoriyasını dəyişdirərək özünü xilas et və oyunu qazan.",
    category: 'MASTERY',
    tier: 'LEGENDARY',
    icon: 'fa-hourglass-end',
    xp: 3000,
    coinReward: 1000,
  },
  {
    id: 'legacy_dies_irae',
    title: 'Dies Irae (Qəzəb Günü)',
    description: "24 nəfərlik Epik masada heç bir hədəfi qaçırmadan və qüsursuz strategiya ilə qalib gəl.",
    category: 'MAFIA',
    tier: 'PLATINUM',
    icon: 'fa-meteor',
    xp: 1500,
    coinReward: 400,
  },
  {
    id: 'legacy_all_tomorrows',
    title: 'All Tomorrows',
    description: "30+ nəfərlik kütləvi xaosun hökm sürdüyü masada Şəhəri mafiyadan təmizləyən əsas qəhrəman ol.",
    category: 'TOWN',
    tier: 'LEGENDARY',
    icon: 'fa-globe',
    xp: 3500,
    coinReward: 1200,
  },
];
