/**
 * TDV BTL MAFIA - 72 Official Achievements Registry
 * Categorized by: Town, Mafia, Neutral, Modes, and Mastery.
 */

import { Achievement } from '../types/achievements';

export const ACHIEVEMENTS_REGISTRY: readonly Achievement[] = [
  // ─── 1. ŞƏHƏR İTTİFAQI (TOWN) ───────────────────────────────────
  {
    id: 'town_sheriff_first_bust',
    title: 'İlk Həbs',
    description: 'Şərif olaraq ilk gecədə Mafiya üzvünü gizli yoxlayıb ifşa et.',
    category: 'TOWN',
    tier: 'BRONZE',
    icon: 'fa-magnifying-glass',
    xp: 150,
    coinReward: 50,
  },
  {
    id: 'town_doctor_miracle_save',
    title: 'Möcüzəvi Qurtuluş',
    description: 'Həkim olaraq qətlin hədəfi olan vətəndaşı gecə həyatda saxla.',
    category: 'TOWN',
    tier: 'SILVER',
    icon: 'fa-user-doctor',
    xp: 300,
    coinReward: 100,
  },
  {
    id: 'town_mayor_triple_hammer',
    title: 'Məclis Hökmü',
    description: 'Bələdiyyə Sədri kimi səlahiyyətini elan edərək x3 səslə mafiyanı edam et.',
    category: 'TOWN',
    tier: 'GOLD',
    icon: 'fa-landmark',
    xp: 500,
    coinReward: 200,
  },
  {
    id: 'town_bodyguard_noble_sacrifice',
    title: 'Fədakar Qalxan',
    description: 'Cangüdən kimi qatili öldürüb dostunun yerinə qəhrəmancasına şəhid ol.',
    category: 'TOWN',
    tier: 'SILVER',
    icon: 'fa-user-shield',
    xp: 350,
    coinReward: 120,
  },
  {
    id: 'town_veteran_triple_kill',
    title: 'Barıt Qoxusu',
    description: 'Qazi kimi gecə həyəcanı zamanı evinə girən 2 və ya daha çox şəxsi güllələ.',
    category: 'TOWN',
    tier: 'PLATINUM',
    icon: 'fa-medal',
    xp: 800,
    coinReward: 350,
  },
  {
    id: 'town_detective_shadow_tracker',
    title: 'Kölgə İzləyicisi',
    description: 'Xəfiyyə olaraq cinayət törədilən evə daxil olan qatilin izini tap.',
    category: 'TOWN',
    tier: 'SILVER',
    icon: 'fa-binoculars',
    xp: 300,
    coinReward: 100,
  },
  {
    id: 'town_coroner_cold_truth',
    title: 'Meyitxanada Həqiqət',
    description: 'Məhkəmə eksperti kimi cəsədi tədqiq edib qətlin silahını və növünü aşkar et.',
    category: 'TOWN',
    tier: 'BRONZE',
    icon: 'fa-microscope',
    xp: 200,
    coinReward: 60,
  },
  {
    id: 'town_citizen_lynch_mafia',
    title: 'Xalqın İntiqamı',
    description: 'Sıravi Vətəndaş olaraq məhkəmədə dəqiq arqumentlə Donu edama göndər.',
    category: 'TOWN',
    tier: 'GOLD',
    icon: 'fa-users',
    xp: 500,
    coinReward: 200,
  },
  {
    id: 'town_martyr_guardian_angel',
    title: 'Əbədi Mələk',
    description: 'Fədai olaraq Şərifi ölümcül zərbədən öz həyatın bahasına qurtar.',
    category: 'TOWN',
    tier: 'SILVER',
    icon: 'fa-shield-heart',
    xp: 350,
    coinReward: 120,
  },
  {
    id: 'town_investigator_duo_check',
    title: 'Şübhəli Şəbəkə',
    description: 'Müstəntiq olaraq eyni fraksiyadan olan iki mafiozu ardıcıl ifşa et.',
    category: 'TOWN',
    tier: 'GOLD',
    icon: 'fa-fingerprint',
    xp: 600,
    coinReward: 250,
  },
  {
    id: 'town_flawless_victory',
    title: 'Pak Şəhər',
    description: 'Şəhər İttifaqı olaraq bir nəfər də günahsız vətəndaş itirmədən qalib gəl.',
    category: 'TOWN',
    tier: 'LEGENDARY',
    icon: 'fa-crown',
    xp: 1500,
    coinReward: 800,
  },
  {
    id: 'town_sheriff_clean_slate',
    title: 'Qüsursuz Təhqiqat',
    description: 'Şərif olaraq 3 ardıcıl gecə mafiya üzvlərini səhvsiz aşkar et.',
    category: 'TOWN',
    tier: 'PLATINUM',
    icon: 'fa-scale-balanced',
    xp: 850,
    coinReward: 400,
  },
  {
    id: 'town_doctor_selfless',
    title: 'Həkim Andı',
    description: 'Həkim olaraq 3 fərqli şəhərlini gecə ölümün pəncəsindən xilas et.',
    category: 'TOWN',
    tier: 'GOLD',
    icon: 'fa-heart-pulse',
    xp: 650,
    coinReward: 250,
  },
  {
    id: 'town_voice_of_reason',
    title: 'Ağıl Səsi',
    description: 'Məhkəmədə günahsız vətəndaşın asılmasına qarşı çıxaraq onu xilas et.',
    category: 'TOWN',
    tier: 'BRONZE',
    icon: 'fa-comment',
    xp: 150,
    coinReward: 50,
  },
  {
    id: 'town_unbreakable_union',
    title: 'Polad İttifaq',
    description: 'Bütün şəhər sakinləri eyni cinayətkarın lehinə yekdilliklə səs versin.',
    category: 'TOWN',
    tier: 'SILVER',
    icon: 'fa-handshake',
    xp: 300,
    coinReward: 100,
  },

  // ─── 2. MAFİYA AİLƏSİ (MAFIA) ───────────────────────────────────
  {
    id: 'mafia_godfather_innocent_mask',
    title: 'Təmiz Əllər',
    description: 'Don olaraq Şərifin yoxlamasından "Məsum Vətəndaş" kimi çıx.',
    category: 'MAFIA',
    tier: 'GOLD',
    icon: 'fa-masks-theater',
    xp: 500,
    coinReward: 200,
  },
  {
    id: 'mafia_first_blood',
    title: 'Qaranlıq Başlanğıc',
    description: 'Mafiya olaraq ilk gecə qətlini uğurla icra et.',
    category: 'MAFIA',
    tier: 'BRONZE',
    icon: 'fa-skull-crossbones',
    xp: 150,
    coinReward: 50,
  },
  {
    id: 'mafia_consort_silence_doctor',
    title: 'Gözbağlayıcının Tələsi',
    description: 'İllüziyaçı olaraq Həkimi bloklayıb qətlin qarşısının alınmasına mane ol.',
    category: 'MAFIA',
    tier: 'SILVER',
    icon: 'fa-wand-magic-sparkles',
    xp: 300,
    coinReward: 120,
  },
  {
    id: 'mafia_blackmail_master',
    title: 'Səssiz Şantaj',
    description: 'Şantajçı olaraq Şərifi susdurub məclisdə ifşa edilməsinin qarşısını al.',
    category: 'MAFIA',
    tier: 'SILVER',
    icon: 'fa-envelope-open-text',
    xp: 350,
    coinReward: 130,
  },
  {
    id: 'mafia_puppeteer_friendly_fire',
    title: 'Kuklanın İpi',
    description: 'Kuklaçı olaraq qatilin hücumunu başqa bir günahsıza yönləndir.',
    category: 'MAFIA',
    tier: 'GOLD',
    icon: 'fa-mask',
    xp: 550,
    coinReward: 220,
  },
  {
    id: 'mafia_forger_fake_will',
    title: 'Saxta Vəsiyyət',
    description: 'Saxtakar olaraq ölmüş şərifin qeydlərini dəyişib şəhəri bir-birinə qat.',
    category: 'MAFIA',
    tier: 'GOLD',
    icon: 'fa-pen-nib',
    xp: 600,
    coinReward: 250,
  },
  {
    id: 'mafia_framer_masterclass',
    title: 'Şər Tələsi',
    description: 'Məsum vətəndaşa şər ataraq Şərifin onu mafioz sanmasına nail ol.',
    category: 'MAFIA',
    tier: 'SILVER',
    icon: 'fa-file-signature',
    xp: 400,
    coinReward: 150,
  },
  {
    id: 'mafia_don_last_standing',
    title: 'Sonuncu Xaç Atası',
    description: 'Bütün digər mafiozlar öldükdən sonra təkbaşına sağ qalıb qalib gəl.',
    category: 'MAFIA',
    tier: 'PLATINUM',
    icon: 'fa-crown',
    xp: 900,
    coinReward: 450,
  },
  {
    id: 'mafia_stealth_kill',
    title: 'Səssiz Qətl',
    description: 'Həkim və ya Cangüdən olan oyunda onların qorumasından yan keçib qətl törət.',
    category: 'MAFIA',
    tier: 'SILVER',
    icon: 'fa-crosshairs',
    xp: 350,
    coinReward: 130,
  },
  {
    id: 'mafia_clean_sweep',
    title: 'Ailənin Triumfu',
    description: 'Mafiya ailəsindən heç kəs edam olunmadan və öldürülmədən qələbə qazan.',
    category: 'MAFIA',
    tier: 'LEGENDARY',
    icon: 'fa-trophy',
    xp: 1600,
    coinReward: 900,
  },
  {
    id: 'mafia_undercover_vote',
    title: 'Taktiki Səs',
    description: 'Öz mafiya yoldaşının edamına səs verərək şəhərlilərin tam etimadını qazan.',
    category: 'MAFIA',
    tier: 'GOLD',
    icon: 'fa-gavel',
    xp: 500,
    coinReward: 200,
  },
  {
    id: 'mafia_night_strike_cap',
    title: 'Qara Zərbə',
    description: 'Gecə qətl limitini tam istifadə edərək eyni gecədə şəhəri iflic et.',
    category: 'MAFIA',
    tier: 'SILVER',
    icon: 'fa-bolt',
    xp: 300,
    coinReward: 100,
  },
  {
    id: 'mafia_paraty_reached',
    title: 'Mütləq Hakimiyyət',
    description: 'Masada mafiya və vətəndaş sayını bərabərləşdirərək oyunu dərhal bitir.',
    category: 'MAFIA',
    tier: 'GOLD',
    icon: 'fa-city',
    xp: 600,
    coinReward: 250,
  },
  {
    id: 'mafia_enforcer_ascend',
    title: 'Yeni Xaç Atası',
    description: 'Sıravi Mafioz kimi Donun ölümündən sonra ailə rəhbərliyini ələ al və qalib gəl.',
    category: 'MAFIA',
    tier: 'SILVER',
    icon: 'fa-gun',
    xp: 400,
    coinReward: 150,
  },
  {
    id: 'mafia_whisper_conspiracy',
    title: 'Gecə Pıçıltısı',
    description: 'Bütün gecə qətllərini gizli qeydə alaraq şübhəsiz tamamla.',
    category: 'MAFIA',
    tier: 'BRONZE',
    icon: 'fa-user-secret',
    xp: 200,
    coinReward: 70,
  },

  // ─── 3. NEYTRAL VƏ XAOS (NEUTRAL) ───────────────────────────────
  {
    id: 'neutral_jester_day_one_hang',
    title: 'Lusiferin Qəhqəhəsi',
    description: 'Dəli (Jester) olaraq ilk 2 gün ərzində özünü edam etdirərək təkbaşına qalib gəl.',
    category: 'NEUTRAL',
    tier: 'PLATINUM',
    icon: 'fa-face-laugh-squint',
    xp: 1000,
    coinReward: 500,
  },
  {
    id: 'neutral_jester_revenge_curse',
    title: 'Məzar Qisası',
    description: 'Edam olunduqdan sonra sənə səs vermiş əsas şəhərliyə lənət yağdıraraq onu məhv et.',
    category: 'NEUTRAL',
    tier: 'GOLD',
    icon: 'fa-skull',
    xp: 550,
    coinReward: 220,
  },
  {
    id: 'neutral_serial_killer_armor',
    title: 'Polad Zireh',
    description: 'Manyak olaraq gecə mafiyanın hücumuna məruz qal və polad jilet sayəsində sağ qal.',
    category: 'NEUTRAL',
    tier: 'SILVER',
    icon: 'fa-shield',
    xp: 350,
    coinReward: 140,
  },
  {
    id: 'neutral_serial_killer_rampage',
    title: 'Qanlı Qisasçı',
    description: 'Seriyalı Qatil kimi 4 oyunçunu ard-arda gecə qətlə yetir.',
    category: 'NEUTRAL',
    tier: 'PLATINUM',
    icon: 'fa-knife',
    xp: 950,
    coinReward: 480,
  },
  {
    id: 'neutral_serial_killer_lone_survivor',
    title: 'Son Nəfəs',
    description: 'Bütün mafiyanı və şəhəri qırıb masada sağ qalan yeganə insan ol.',
    category: 'NEUTRAL',
    tier: 'LEGENDARY',
    icon: 'fa-fire',
    xp: 1750,
    coinReward: 1000,
  },
  {
    id: 'neutral_arsonist_mass_ignition',
    title: 'Böyük Qığılcım',
    description: 'Arsonist olaraq eyni gecədə 4 və ya daha çox benzillənmiş evi alova bürü.',
    category: 'NEUTRAL',
    tier: 'LEGENDARY',
    icon: 'fa-fire-flame-curved',
    xp: 1800,
    coinReward: 1000,
  },
  {
    id: 'neutral_amnesiac_remember_mafia',
    title: 'Qaranlıq Yaddaş',
    description: 'Kimlik Axtaran kimi ölmüş Donun rolunu xatırlayaraq mafiyaya rəhbərlik et.',
    category: 'NEUTRAL',
    tier: 'GOLD',
    icon: 'fa-brain',
    xp: 600,
    coinReward: 250,
  },
  {
    id: 'neutral_amnesiac_remember_sheriff',
    title: 'Ədalətin Qayıdışı',
    description: 'Kimlik Axtaran kimi ölmüş Şərifin nişanını götürərək şəhəri xilas et.',
    category: 'NEUTRAL',
    tier: 'GOLD',
    icon: 'fa-shield-halved',
    xp: 600,
    coinReward: 250,
  },
  {
    id: 'neutral_witch_puppets_killer',
    title: 'Ruh İdarəsi',
    description: 'Cadugər kimi Seriyalı Qatili hipnoz edərək onu Mafiya üzvünün üstünə göndər.',
    category: 'NEUTRAL',
    tier: 'PLATINUM',
    icon: 'fa-wand-sparkles',
    xp: 850,
    coinReward: 400,
  },
  {
    id: 'neutral_yakuza_clan_expansion',
    title: 'Samuray Paktı',
    description: 'Yakuza Klanı olaraq Qərb mafiyasının bütün tələlərini dəf et.',
    category: 'NEUTRAL',
    tier: 'GOLD',
    icon: 'fa-dragon',
    xp: 650,
    coinReward: 280,
  },
  {
    id: 'neutral_void_portal_open',
    title: 'Qaranlıq Portal',
    description: 'Boşluq Təriqətçisi olaraq 3 oyunçunu işarələyib ayini tamamla.',
    category: 'NEUTRAL',
    tier: 'PLATINUM',
    icon: 'fa-eye',
    xp: 900,
    coinReward: 450,
  },
  {
    id: 'neutral_chaos_diplomat',
    title: 'Xaos Diplomatı',
    description: 'Heç bir fraksiyanın hədəfinə tuş gəlmədən 5 raund sağ qal.',
    category: 'NEUTRAL',
    tier: 'SILVER',
    icon: 'fa-scale-unbalanced',
    xp: 400,
    coinReward: 160,
  },

  // ─── 4. XÜSUSİ REJİMLƏR & MİNİ-OYUNLAR (MODES) ───────────────────
  {
    id: 'mode_inferno_ninth_circle',
    title: 'Kokit Buzlağı',
    description: "Dante's Inferno rejimində bütün 9 dairədən keçərək sonuncu buzlu dairəyə çat.",
    category: 'MODES',
    tier: 'LEGENDARY',
    icon: 'fa-snowflake',
    xp: 2000,
    coinReward: 1200,
  },
  {
    id: 'mode_inferno_heresy_decoder',
    title: 'Təriqət Şifrəsi',
    description: 'Heresy dairəsində sızan gizli ipucunu deşifrə edib qatili tap.',
    category: 'MODES',
    tier: 'SILVER',
    icon: 'fa-key',
    xp: 350,
    coinReward: 140,
  },
  {
    id: 'mode_inferno_greed_debt',
    title: 'Tamah Cəzası',
    description: 'Greed dairəsində əlavə səs borcunu qızıllarla ödəyərək edamdan qurtul.',
    category: 'MODES',
    tier: 'GOLD',
    icon: 'fa-coins',
    xp: 550,
    coinReward: 230,
  },
  {
    id: 'mode_earth_klaatu_freeze',
    title: 'Zaman Dayandı',
    description: 'The Day The Earth Stood Still rejimində dünyanı dondurub qətlin qarşısını al.',
    category: 'MODES',
    tier: 'GOLD',
    icon: 'fa-icicles',
    xp: 600,
    coinReward: 250,
  },
  {
    id: 'mode_earth_doomsday_survival',
    title: 'Qiyamət Saatı 11:59',
    description: 'Doomsday saatı 11-ə çatdıqda şəhəri məhv olmaqdan xilas et.',
    category: 'MODES',
    tier: 'PLATINUM',
    icon: 'fa-clock-rotate-left',
    xp: 900,
    coinReward: 450,
  },
  {
    id: 'mode_valkyrie_bomb_defusal',
    title: 'Çamadanın Sirri',
    description: 'Valkyrie rejimində partlayıcı çamadanı vaxt bitmədən zərərsizləşdir.',
    category: 'MODES',
    tier: 'GOLD',
    icon: 'fa-briefcase',
    xp: 650,
    coinReward: 280,
  },
  {
    id: 'mode_valkyrie_dictator_down',
    title: 'Tiranın Süqutu',
    description: 'Valkyrie əməliyyatında Diktatoru məhkəmədə və ya qəsdlə devir.',
    category: 'MODES',
    tier: 'SILVER',
    icon: 'fa-person-falling-burst',
    xp: 400,
    coinReward: 150,
  },
  {
    id: 'mode_stanford_revolt_spark',
    title: 'Həbsxana Qiyamı',
    description: 'Stanford Prison rejimində Qiyam göstəricisini 100%-ə çatdırıb qələbə qazan.',
    category: 'MODES',
    tier: 'GOLD',
    icon: 'fa-link-slash',
    xp: 700,
    coinReward: 300,
  },
  {
    id: 'mode_catenaccio_wall_breach',
    title: 'Beton Sədd',
    description: 'Catenaccio rejimində 4 nəfərlik müdafiə divarını yaran snayperi tap.',
    category: 'MODES',
    tier: 'SILVER',
    icon: 'fa-shield-halved',
    xp: 400,
    coinReward: 160,
  },
  {
    id: 'mode_chernobyl_radiation_shield',
    title: 'Sarkofaq Zirehi',
    description: 'Çernobıl rejimində dozimetristlə radiasiya dərəcəsini sıfırla.',
    category: 'MODES',
    tier: 'GOLD',
    icon: 'fa-biohazard',
    xp: 600,
    coinReward: 250,
  },
  {
    id: 'mode_cyberpunk_neural_hack',
    title: 'Neo-Bakı Netrunneri',
    description: 'Cyberpunk rejimində qara şəbəkə xakerini izləyərək sistemini çökdür.',
    category: 'MODES',
    tier: 'GOLD',
    icon: 'fa-network-wired',
    xp: 650,
    coinReward: 280,
  },
  {
    id: 'mode_bermuda_ghost_fleet',
    title: 'Kabus Donanması',
    description: 'Bermud Üçbucağında itkin düşmüş dənizçilərin sirrini aşkar et.',
    category: 'MODES',
    tier: 'SILVER',
    icon: 'fa-anchor',
    xp: 350,
    coinReward: 140,
  },
  {
    id: 'mode_baker_street_holmes_mind',
    title: 'Elementar, Vatson!',
    description: 'Baker Street rejimində Moriartinin bütün şəbəkəsini 3 raunda ifşa et.',
    category: 'MODES',
    tier: 'PLATINUM',
    icon: 'fa-magnifying-glass-chart',
    xp: 950,
    coinReward: 480,
  },
  {
    id: 'mode_all_in_governance_architect',
    title: 'Böyük Arxitektor',
    description: 'All-In 50 nəfərlik rejimdə Arxitektor açarını uğurla təsdiqlə.',
    category: 'MODES',
    tier: 'GOLD',
    icon: 'fa-compass-drafting',
    xp: 750,
    coinReward: 320,
  },
  {
    id: 'mode_all_in_district_caucus',
    title: 'Kvartal Lideri',
    description: 'All-In rejimində Kommersiya kvartalının lideri seçilərək mərkəzə nümayəndə göndər.',
    category: 'MODES',
    tier: 'SILVER',
    icon: 'fa-landmark-flag',
    xp: 450,
    coinReward: 180,
  },
  {
    id: 'mode_all_in_fifty_players',
    title: 'Meqapolis Şərəfi',
    description: '40+ nəfərlik All-In oyununu əvvəldən axıra kimi tamamla.',
    category: 'MODES',
    tier: 'LEGENDARY',
    icon: 'fa-gem',
    xp: 2200,
    coinReward: 1500,
  },

  // ─── 5. USTA DEDUKTİV VƏ PSİXOLOGİYA (MASTERY) ────────────────────
  {
    id: 'mastery_speed_detective',
    title: 'İldırım Deduksiya',
    description: 'Gündüz müzakirəsinin ilk 30 saniyəsində əsl qatili ifşa et.',
    category: 'MASTERY',
    tier: 'SILVER',
    icon: 'fa-bolt-lightning',
    xp: 400,
    coinReward: 150,
  },
  {
    id: 'mastery_clutch_defense',
    title: '30 Saniyəlik Möcüzə',
    description: 'Məhkəmə kürsüsündə son söz zamanı şəhərliləri fikrindən daşındırıb bəraət al.',
    category: 'MASTERY',
    tier: 'GOLD',
    icon: 'fa-bullhorn',
    xp: 600,
    coinReward: 250,
  },
  {
    id: 'mastery_unanimous_verdict',
    title: 'Yekdil Məhkəmə',
    description: 'Məhkəmədə bütün masanın 100% "Edam" səsini qazanaraq qatili as.',
    category: 'MASTERY',
    tier: 'SILVER',
    icon: 'fa-square-check',
    xp: 350,
    coinReward: 130,
  },
  {
    id: 'mastery_poker_face',
    title: 'Emosiyasız Simam',
    description: 'Bütün oyun boyu bir dəfə də olsun şübhə altına düşmədən qalib gəl.',
    category: 'MASTERY',
    tier: 'GOLD',
    icon: 'fa-face-meh',
    xp: 650,
    coinReward: 280,
  },
  {
    id: 'mastery_voice_orator',
    title: 'Böyük Natiq',
    description: 'WebRTC səsli çatda danışaraq masadakı 3 qərarsız oyunçunun səsini yönləndir.',
    category: 'MASTERY',
    tier: 'SILVER',
    icon: 'fa-microphone',
    xp: 400,
    coinReward: 160,
  },
  {
    id: 'mastery_night_owl',
    title: 'Gecə Qartalı',
    description: 'Gecə əmrini son 3 saniyədə göndərərək gözlənilməz dönüş yarat.',
    category: 'MASTERY',
    tier: 'BRONZE',
    icon: 'fa-feather',
    xp: 200,
    coinReward: 80,
  },
  {
    id: 'mastery_gemini_bot_whisperer',
    title: 'AI Strateqi',
    description: 'Masada 5 bot olan oyunda botların davranışını oxuyaraq qələbə qazan.',
    category: 'MASTERY',
    tier: 'SILVER',
    icon: 'fa-robot',
    xp: 450,
    coinReward: 180,
  },
  {
    id: 'mastery_ten_game_streak',
    title: 'Qızıl Seriya',
    description: 'Ard-arda 10 oyunda qalib gələrək lisey rekordunu qır.',
    category: 'MASTERY',
    tier: 'LEGENDARY',
    icon: 'fa-fire',
    xp: 2500,
    coinReward: 1500,
  },
  {
    id: 'mastery_five_game_streak',
    title: 'Gümüş Seriya',
    description: 'Ard-arda 5 oyunda qələbə qazan.',
    category: 'MASTERY',
    tier: 'PLATINUM',
    icon: 'fa-star',
    xp: 1200,
    coinReward: 600,
  },
  {
    id: 'mastery_fifty_games_played',
    title: 'Lisey Veteranı',
    description: 'Ümumilikdə 50 tam mafiya oyunu oyna.',
    category: 'MASTERY',
    tier: 'GOLD',
    icon: 'fa-shield-halved',
    xp: 800,
    coinReward: 400,
  },
  {
    id: 'mastery_hundred_games_played',
    title: 'Mafiya Əfsanəsi',
    description: 'Ümumilikdə 100 mafiya oyunu tamamla.',
    category: 'MASTERY',
    tier: 'LEGENDARY',
    icon: 'fa-medal',
    xp: 3000,
    coinReward: 2000,
  },
  {
    id: 'mastery_anti_afk_sentinel',
    title: 'Etibarlı Oyunçu',
    description: '20 oyun boyu heç vaxt AFK qalmadan tam iştirak et.',
    category: 'MASTERY',
    tier: 'SILVER',
    icon: 'fa-user-check',
    xp: 450,
    coinReward: 200,
  },
  {
    id: 'mastery_coin_collector',
    title: 'Lisey Xəzinədarı',
    description: 'Qələbələrdən və nailiyyətlərdən ümumilikdə 10,000 🪙 qızıl topla.',
    category: 'MASTERY',
    tier: 'PLATINUM',
    icon: 'fa-sack-dollar',
    xp: 1400,
    coinReward: 700,
  },
  {
    id: 'mastery_all_modes_played',
    title: 'Eksperimentator',
    description: 'Mövcud olan bütün 15 oyun formatını ən azı 1 dəfə sınaqdan keçir.',
    category: 'MASTERY',
    tier: 'LEGENDARY',
    icon: 'fa-compass',
    xp: 2000,
    coinReward: 1200,
  },
];
